//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.DBConnectorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBConnectorService.IDBConnectorService")]
    public interface IDBConnectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/AddUser", ReplyAction="http://tempuri.org/IDBConnectorService/AddUserResponse")]
        string AddUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/AddUser", ReplyAction="http://tempuri.org/IDBConnectorService/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBConnectorServiceChannel : ClientSide.DBConnectorService.IDBConnectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBConnectorServiceClient : System.ServiceModel.ClientBase<ClientSide.DBConnectorService.IDBConnectorService>, ClientSide.DBConnectorService.IDBConnectorService {
        
        public DBConnectorServiceClient() {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(string user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(string user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
