//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.RandomizerServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandomizerServer.IDBConnectorService")]
    public interface IDBConnectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/AddUser", ReplyAction="http://tempuri.org/IDBConnectorService/AddUserResponse")]
        string AddUser(DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/AddUser", ReplyAction="http://tempuri.org/IDBConnectorService/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/GetAllUsers", ReplyAction="http://tempuri.org/IDBConnectorService/GetAllUsersResponse")]
        DBModels.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBConnectorService/GetAllUsers", ReplyAction="http://tempuri.org/IDBConnectorService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<DBModels.User[]> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBConnectorServiceChannel : ClientSide.RandomizerServer.IDBConnectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBConnectorServiceClient : System.ServiceModel.ClientBase<ClientSide.RandomizerServer.IDBConnectorService>, ClientSide.RandomizerServer.IDBConnectorService {
        
        public DBConnectorServiceClient() {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBConnectorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(DBModels.User user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(DBModels.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public DBModels.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<DBModels.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
