//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.RandomizerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandomizerService.IRandomizerService")]
    public interface IRandomizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/AddUser", ReplyAction="http://tempuri.org/IRandomizerService/AddUserResponse")]
        void AddUser(DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/AddUser", ReplyAction="http://tempuri.org/IRandomizerService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(DBModels.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/GetAllUsers", ReplyAction="http://tempuri.org/IRandomizerService/GetAllUsersResponse")]
        DBModels.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/GetAllUsers", ReplyAction="http://tempuri.org/IRandomizerService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<DBModels.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/AddRequest", ReplyAction="http://tempuri.org/IRandomizerService/AddRequestResponse")]
        void AddRequest(System.Guid userGuid, DBModels.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/AddRequest", ReplyAction="http://tempuri.org/IRandomizerService/AddRequestResponse")]
        System.Threading.Tasks.Task AddRequestAsync(System.Guid userGuid, DBModels.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/GetAllRequests", ReplyAction="http://tempuri.org/IRandomizerService/GetAllRequestsResponse")]
        DBModels.Request[] GetAllRequests(System.Guid userGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRandomizerService/GetAllRequests", ReplyAction="http://tempuri.org/IRandomizerService/GetAllRequestsResponse")]
        System.Threading.Tasks.Task<DBModels.Request[]> GetAllRequestsAsync(System.Guid userGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRandomizerServiceChannel : ClientSide.RandomizerService.IRandomizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandomizerServiceClient : System.ServiceModel.ClientBase<ClientSide.RandomizerService.IRandomizerService>, ClientSide.RandomizerService.IRandomizerService {
        
        public RandomizerServiceClient() {
        }
        
        public RandomizerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RandomizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandomizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(DBModels.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(DBModels.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public DBModels.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<DBModels.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void AddRequest(System.Guid userGuid, DBModels.Request request) {
            base.Channel.AddRequest(userGuid, request);
        }
        
        public System.Threading.Tasks.Task AddRequestAsync(System.Guid userGuid, DBModels.Request request) {
            return base.Channel.AddRequestAsync(userGuid, request);
        }
        
        public DBModels.Request[] GetAllRequests(System.Guid userGuid) {
            return base.Channel.GetAllRequests(userGuid);
        }
        
        public System.Threading.Tasks.Task<DBModels.Request[]> GetAllRequestsAsync(System.Guid userGuid) {
            return base.Channel.GetAllRequestsAsync(userGuid);
        }
    }
}
